name: Linteo

on: push

jobs: 
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Lint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint